import Navbar from "./navbar";
import HeroSlider from "./HeroSlider";

export default function Home() {
  return (
      <div className="home">
            {/* Navbar */}
                  <Navbar />

                        {/* Slider */}
                              <div style={{ marginTop: "60px" }}>
                                      <HeroSlider />
                                            </div>

                                                  {/* İçerik Bölümü */}
                                                        <section
                                                                style={{
                                                                          padding: "60px 20px",
                                                                                    maxWidth: "1100px",
                                                                                              margin: "0 auto",
                                                                                                        textAlign: "center"
                                                                                                                }}
                                                                                                                      >
                                                                                                                              <h1
                                                                                                                                        style={{
                                                                                                                                                    fontSize: "2.5rem",
                                                                                                                                                                fontWeight: "700",
                                                                                                                                                                            marginBottom: "20px",
                                                                                                                                                                                      }}
                                                                                                                                                                                              >
                                                                                                                                                                                                        Atlantik Nuts — Global Kalite Standartları
                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                        <p
                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                              fontSize: "1.2rem",
                                                                                                                                                                                                                                                          lineHeight: "1.7",
                                                                                                                                                                                                                                                                      color: "#555",
                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                  17 yıllık tecrübemizle ceviz, kuru meyve ve doğal ürünleri dünyanın dört bir yanına ihraç ediyoruz.
                                                                                                                                                                                                                                                                                                            Üretimden paketlemeye kadar her adımda kalite, hijyen ve sürdürülebilirlik önceliğimizdir.
                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                {/* Footer */}
                                                                                                                                                                                                                                                                                                                                      <footer
                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                        background: "#111",
                                                                                                                                                                                                                                                                                                                                                                  color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                            padding: "40px 20px",
                                                                                                                                                                                                                                                                                                                                                                                      textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                marginTop: "40px",
                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ marginBottom: "6px" }}>© 2025 Atlantik Nuts</p>
                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={{ opacity: 0.6 }}>Tüm hakları saklıdır</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                          }