// =====================================================
//  LANG.JS — Atlantik Nuts Çoklu Dil Sistemi (v2.0)
// =====================================================

// ------------------------------------------
// 1) DİL VERİ TABANI
// ------------------------------------------
const translations = {
    tr: {
            home: "Ana Sayfa",
                    about: "Hakkımızda",
                            products: "Ürünler",
                                    services: "Hizmetler",
                                            projects: "Projeler",
                                                    certificates: "Sertifikalar",
                                                            contact: "İletişim",

                                                                    hero_title: "Atlantik Nuts",
                                                                            hero_sub: "Premium Kuruyemiş – Global Tedarik"
                                                                                },

                                                                                    en: {
                                                                                            home: "Home",
                                                                                                    about: "About Us",
                                                                                                            products: "Products",
                                                                                                                    services: "Services",
                                                                                                                            projects: "Projects",
                                                                                                                                    certificates: "Certificates",
                                                                                                                                            contact: "Contact",

                                                                                                                                                    hero_title: "Atlantik Nuts",
                                                                                                                                                            hero_sub: "Premium Nuts – Global Supply"
                                                                                                                                                                },

                                                                                                                                                                    es: {
                                                                                                                                                                            home: "Inicio",
                                                                                                                                                                                    about: "Sobre Nosotros",
                                                                                                                                                                                            products: "Productos",
                                                                                                                                                                                                    services: "Servicios",
                                                                                                                                                                                                            projects: "Proyectos",
                                                                                                                                                                                                                    certificates: "Certificados",
                                                                                                                                                                                                                            contact: "Contacto",

                                                                                                                                                                                                                                    hero_title: "Atlantik Nuts",
                                                                                                                                                                                                                                            hero_sub: "Frutos Secos Premium – Suministro Global"
                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                    ar: {
                                                                                                                                                                                                                                                            home: "الصفحة الرئيسية",
                                                                                                                                                                                                                                                                    about: "معلومات عنا",
                                                                                                                                                                                                                                                                            products: "المنتجات",
                                                                                                                                                                                                                                                                                    services: "الخدمات",
                                                                                                                                                                                                                                                                                            projects: "المشاريع",
                                                                                                                                                                                                                                                                                                    certificates: "الشهادات",
                                                                                                                                                                                                                                                                                                            contact: "اتصل بنا",

                                                                                                                                                                                                                                                                                                                    hero_title: "Atlantik Nuts",
                                                                                                                                                                                                                                                                                                                            hero_sub: "مكسرات فاخرة – توريد عالمي"
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                };


                                                                                                                                                                                                                                                                                                                                // ------------------------------------------
                                                                                                                                                                                                                                                                                                                                // 2) DİL AYARINI KAYDET
                                                                                                                                                                                                                                                                                                                                // ------------------------------------------
                                                                                                                                                                                                                                                                                                                                function setLanguage(lang) {
                                                                                                                                                                                                                                                                                                                                    localStorage.setItem("site-lang", lang);
                                                                                                                                                                                                                                                                                                                                        applyLanguage();
                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                        // ------------------------------------------
                                                                                                                                                                                                                                                                                                                                        // 3) HTML ÜZERİNE DİLİ UYGULA
                                                                                                                                                                                                                                                                                                                                        // ------------------------------------------
                                                                                                                                                                                                                                                                                                                                        function applyLanguage() {
                                                                                                                                                                                                                                                                                                                                            const lang = localStorage.getItem("site-lang") || "tr";

                                                                                                                                                                                                                                                                                                                                                // Tüm elemanları topla: text, attr-text, placeholders vs.
                                                                                                                                                                                                                                                                                                                                                    const elements = document.querySelectorAll("[data-lang]");

                                                                                                                                                                                                                                                                                                                                                        elements.forEach(el => {
                                                                                                                                                                                                                                                                                                                                                                const key = el.getAttribute("data-lang");

                                                                                                                                                                                                                                                                                                                                                                        // Çeviri varsa uygula, yoksa fallback (TR)
                                                                                                                                                                                                                                                                                                                                                                                const text = translations[lang]?.[key] || translations["tr"][key] || key;

                                                                                                                                                                                                                                                                                                                                                                                        // Placeholder form alanları için
                                                                                                                                                                                                                                                                                                                                                                                                if (el.hasAttribute("data-lang-placeholder")) {
                                                                                                                                                                                                                                                                                                                                                                                                            el.placeholder = text;
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                            // Title çevirisi
                                                                                                                                                                                                                                                                                                                                                                                                                                    else if (el.hasAttribute("data-lang-title")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                el.title = text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Alt text çevirisi (img)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else if (el.hasAttribute("data-lang-alt")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    el.alt = text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Normal text için
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        el.textContent = text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 4) SAYFA YÜKLENİNCE UYGULA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener("DOMContentLoaded", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        applyLanguage();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // RTL dilleri otomatik ayarla (Arapça)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const lang = localStorage.getItem("site-lang") || "tr";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.documentElement.dir = (lang === "ar") ? "rtl" : "ltr";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });